version: "3"

services:
  solr:
    image: solr:8.8.2
      #    logging:
      #      driver: none
    command: solr-precreate techproducts
    ports:
    - "8983:8983"
  integration_tests:
    image: mcr.microsoft.com/dotnet/sdk:5.0-alpine
    depends_on:
    - solr
    volumes:
    - .:/code
    - $HOME/.nuget:/root/.nuget
    working_dir: /code
    command: dotnet test SolrNet.Tests.Integration --filter 'Category=Integration'



